Experiment 4

In [ ]:
import tensorflow as tf
import numpy as np

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

class CustomDNN:
    def __init__(self, learning_rate=0.01):
        self.learning_rate = learning_rate

        # Initialize weights
        self.w1 = np.random.randn(784, 128) * 0.01
        self.b1 = np.zeros((1, 128))
        self.w2 = np.random.randn(128, 32) * 0.01
        self.b2 = np.zeros((1, 32))
        self.w3 = np.random.randn(32, 10) * 0.01
        self.b3 = np.zeros((1, 10))

    def relu(self, Z):
        return np.maximum(0, Z)

    def relu_derivative(self, Z):
        return Z > 0

    def softmax(self, Z):
        expZ = np.exp(Z - np.max(Z, axis=1, keepdims=True))
        return expZ / np.sum(expZ, axis=1, keepdims=True)

    def forward(self, X):
        self.Z1 = np.dot(X, self.w1) + self.b1
        self.A1 = self.relu(self.Z1)
        self.Z2 = np.dot(self.A1, self.w2) + self.b2
        self.A2 = self.relu(self.Z2)
        self.Z3 = np.dot(self.A2, self.w3) + self.b3
        self.A3 = self.softmax(self.Z3)
        return self.A3

    def backward(self, X, y):
        m = y.shape[0]

        # Gradients for the last layer
        dZ3 = self.A3 - y
        dW3 = (1/m) * np.dot(self.A2.T, dZ3)
        dB3 = (1/m) * np.sum(dZ3, axis=0, keepdims=True)

        # Gradients for the second layer
        dA2 = np.dot(dZ3, self.w3.T)
        dZ2 = dA2 * self.relu_derivative(self.Z2)
        dW2 = (1/m) * np.dot(self.A1.T, dZ2)
        dB2 = (1/m) * np.sum(dZ2, axis=0, keepdims=True)

        # Gradients for the first layer
        dA1 = np.dot(dZ2, self.w2.T)
        dZ1 = dA1 * self.relu_derivative(self.Z1)
        dW1 = (1/m) * np.dot(X.T, dZ1)
        dB1 = (1/m) * np.sum(dZ1, axis=0, keepdims=True)


        self.w3 -= self.learning_rate * dW3
        self.b3 -= self.learning_rate * dB3
        self.w2 -= self.learning_rate * dW2
        self.b2 -= self.learning_rate * dB2
        self.w1 -= self.learning_rate * dW1
        self.b1 -= self.learning_rate * dB1

        return dW1, dB1, dW2, dB2, dW3, dB3

    def train(self, X, y, epochs):
        for epoch in range(epochs):
            output = self.forward(X)
            dW1, dB1, dW2, dB2, dW3, dB3 = self.backward(X, y)

            print(f"Epoch {epoch + 1}/{epochs}")
            print(f"dW1:\n{dW1}\ndB1:\n{dB1}")
            print(f"dW2:\n{dW2}\ndB2:\n{dB2}")
            print(f"dW3:\n{dW3}\ndB3:\n{dB3}")
            print(f"Updated weights and biases after epoch {epoch + 1}.\n")
            print("-" * 50)


model = CustomDNN()
model.train(X_train.reshape(-1, 784), y_train, epochs=5)


Epoch 1/5
dW1:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
dB1:
[[ 1.68898714e-05  3.52057155e-05  8.63233838e-06 -1.33300862e-05
  -5.81806416e-07 -1.12020206e-05  3.46639015e-05  8.90834724e-06
   3.23244956e-05  1.50347429e-06 -6.31539294e-05 -1.38860100e-06
  -3.38722293e-05  1.50369457e-05 -5.88925113e-05  3.52054932e-05
   1.52856104e-05 -2.23218647e-05 -3.55308775e-07  1.18575848e-05
  -1.39785168e-05  1.84902240e-05 -2.53089615e-05 -1.58879967e-05
   9.42778795e-06 -1.71717412e-05  1.01129597e-05  2.58783113e-05
   3.89745188e-06  4.38054178e-06 -1.76980394e-05 -1.00572049e-05
  -1.97140092e-05 -3.84246865e-05  4.24081731e-06 -2.03082674e-05
   5.73192475e-06 -7.03188818e-06  4.76306154e-05 -6.74285110e-05
   8.09679379e-06 -1.59299119e-05  6.62040009e-05 -1.63689062e-05
  -2.39189398e-05  3.47175974e-05  2.16197289e-06 -1.38865427e-05
   2.02741406e-05  8.96777417e-0